### ISSUE TITLE
Prefix parameters with namespace

### ISSUE THREAD

**Issue by ianshward** [mapbox/lambda-cfn#6]
To avoid parameter name collisions, parameter names should be prefixed with the name of the rule.

**Comment by zmully** [comment]
So a couple of problems I've discovered with this. I don't think the rule parameters shouldn't know or care about their namespace, but when the parameters are namespaced this breaks the function.

Right now, I've got it namespacing the parameters during template generation, which is then fed to streambot in the format 'repositoryRulenameParametername'. When the function runs and Streambot sets its environment, the function is looking for 'Parametername' not 'repositoryRulenameParametername'. 

Because the repository name is determined at runtime, I think that we could namespace the parameters by providing a helper function in lambda-cfn to generate the correct parameter names. 

I haven't figured out exactly how the helper function would derive the correct parameter names though... so this may not be possible without changing the rule format.

**Comment by zmully** [comment]
fixed by #29
